version: '3.9'

services:

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: miserss/foodgram_backend:v1
    restart: always
    volumes:
      - static_volume:/app/backend/static/
      - media_volume:/app/backend/media/
    depends_on:
     - db
    env_file:
      - ./.env

  frontend:
    image: miserss/foodgram_frontend:v1
    volumes:
      - frontend_volume:/app/result_build/build/
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/:/etc/nginx/conf.d/default.conf
      - frontend_volume:/usr/share/nginx/html/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - frontend

volumes:
  postgresql_volume:
  static_volume:
  media_volume:
  frontend_volume: