version: '3.9'

services:

  db:
    image: postgres:13
    platform: linux/amd64
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: miserss/foodgram_backend:v3
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on:
      - db

  frontend:
    image: miserss/foodgram_frontend:v1
    platform: linux/amd64
    volumes:
      - frontend_volume:/app/result_build/build/

  nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - ./nginx.conf/:/etc/nginx/conf.d/default.conf
      - frontend_volume:/usr/share/nginx/html/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/

volumes:
  pg_data:
  static_volume:
  media_volume:
  frontend_volume:
