version: '3.3'

services:

  db:
    image: postgres:13
    platform: linux/amd64
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: miserss/foodgram_backend
    platform: linux/amd64
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./.env

  frontend:
    image: miserss/foodgram_frontend
    platform: linux/amd64
    volumes:
      - frontend_volume:/app/result_build/build/
    env_file: .env

  nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - ./nginx.conf/:/etc/nginx/conf.d/default.conf
      - frontend_volume:/usr/share/nginx/html/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    env_file: .env
    depends_on:
      - db

volumes:
  pg_data:
  static_volume:
  media_volume:
  frontend_volume:

